language: python
python:
- 3.9
- 3.8
- 3.7
install:
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.7
    all_branches: true
  password:
    secure: EsrkgskQX6T8AWix0yr8AW5RYk/UjNGWvMDviVjW7C9Re99PIqjOX4nuismD8iu/u80pJ57ND7DBrejN606i+TjxUpiofghceY3VGYPS6STHHqr3ncmEWJkG7UqCK+1s5nNyhhy1/5BVfionL5gNg0cwkOkPdIRPdzqjjcv2kM+vsBqRT9Aj7SIWu9it+5MX56I/0NgcSLGaljETUAVBBo7h/B3Asb8pJf7NdGc9Dybze3zck0MLCZJp82FV2cN/U0kOxpDkEaOZkfB5wQVYOgWU3Oy3JAiLXIHLpT5jXiAgkvE+YO1QcJvePORawpTNyAqjwtVPPFSeVeKVXK9pbDYJTQ7y3y7VlN3RfpcSX1mvbBChLbZ7GCXOeXFVqzrd/qoJWRt6ZDIGzxrD0IjFx/P0+B/6dGMgldwLaHCisaz//MpQZikS6rd1BFz/OtdKWl+PNmgzsO4n8IvUWhC7BeRGd7Lt9/PbbSuGSqTIaSt3uT7cy4ZOI4o1yyv5WoNV4XjdDyHvLnwOcHXt352pEvYT8/Qq0DJpAgvk0MOD1g4rlpCN9BocSTg+sewwCf/69NvBKYV28b1HwtdDIj9oZRbRcit2ilJawZr3VBGhprn7kMPmml1Yx2ztg3V03+31nrqDDUu7+1YMYW4ubI+IlSiGhcYBedgVefYqeEH4KXI=
